/* Autogenerated self-contained lessons for every task — A0→C2+ */
const LESSONS = {
  "a0-u1-t1": {
    "goal": "24 Yunanca harfi tanı, büyük/küçük eşleştir, yüksek sesle söyle.",
    "theory": [
      "Modern Yunanca alfabesi 24 harftir. Latin alfabesinden tanıdık görünenler farklı ses çıkarabilir (Β=v, Η=i, Ρ=r, Χ=h/kh).",
      "Her harfin büyük ve küçük hali vardır. Ezber sırası: Α Β Γ Δ Ε Ζ Η Θ Ι Κ Λ Μ Ν Ξ Ο Π Ρ Σ Τ Υ Φ Χ Ψ Ω.",
      "Σ sonunda ς yazılır (ör. καλός). Bu kuralı şimdiden alışkanlık yap."
    ],
    "examples": [
      {
        "el": "Α α",
        "tr": "alfa"
      },
      {
        "el": "Β β",
        "tr": "vita (v)"
      },
      {
        "el": "Γ γ",
        "tr": "gama"
      },
      {
        "el": "Δ δ",
        "tr": "delta"
      },
      {
        "el": "Ε ε",
        "tr": "epsilon"
      },
      {
        "el": "Ζ ζ",
        "tr": "zita"
      },
      {
        "el": "Η η",
        "tr": "ita (i)"
      },
      {
        "el": "Θ θ",
        "tr": "thita"
      },
      {
        "el": "Ι ι",
        "tr": "yota (i)"
      },
      {
        "el": "Κ κ",
        "tr": "kapa"
      },
      {
        "el": "Λ λ",
        "tr": "lamda"
      },
      {
        "el": "Μ μ",
        "tr": "mi"
      },
      {
        "el": "Ν ν",
        "tr": "ni"
      },
      {
        "el": "Ξ ξ",
        "tr": "ksi"
      },
      {
        "el": "Ο ο",
        "tr": "omikron"
      },
      {
        "el": "Π π",
        "tr": "pi"
      },
      {
        "el": "Ρ ρ",
        "tr": "ro"
      },
      {
        "el": "Σ σ/ς",
        "tr": "sigma"
      },
      {
        "el": "Τ τ",
        "tr": "taf"
      },
      {
        "el": "Υ υ",
        "tr": "ipsilon (i)"
      },
      {
        "el": "Φ φ",
        "tr": "fi"
      },
      {
        "el": "Χ χ",
        "tr": "hi"
      },
      {
        "el": "Ψ ψ",
        "tr": "psi"
      },
      {
        "el": "Ω ω",
        "tr": "omega (o)"
      }
    ],
    "steps": [
      "Α–Ω sırayla deftere büyük+küçük yaz (Αα Ββ … Ωω).",
      "Her harfi yüksek sesle adıyla söyle (alfa, vita…).",
      "Karışık 12 harf kartı yap: büyük göster → küçük yaz; küçük göster → adı söyle.",
      "Uygulamada Kartlar → Alfabe antrenmanını 1 tur bitir."
    ],
    "practice": [
      "Büyük/küçük eşleştirme: Α-α, Β-β… hepsini hatasız yap.",
      "Σ / ς farkını 5 kelimede göster: καλός, της, σας, πως, ένας."
    ],
    "check": [
      "24 harfi sırasız sorunca adını söyleyebiliyor musun?",
      "ς sadece kelime sonunda mı kullanıyorsun?"
    ],
    "table": {
      "title": "Alfabe",
      "headers": [
        "Büyük",
        "Küçük",
        "Ad",
        "Ses notu"
      ],
      "rows": [
        [
          "Α",
          "α",
          "alfa",
          "a"
        ],
        [
          "Β",
          "β",
          "vita",
          "v"
        ],
        [
          "Γ",
          "γ",
          "gama",
          "g/y"
        ],
        [
          "Δ",
          "δ",
          "delta",
          "ð"
        ],
        [
          "Ε",
          "ε",
          "epsilon",
          "e"
        ],
        [
          "Ζ",
          "ζ",
          "zita",
          "z"
        ],
        [
          "Η",
          "η",
          "ita",
          "i"
        ],
        [
          "Θ",
          "θ",
          "thita",
          "th"
        ],
        [
          "Ι",
          "ι",
          "yota",
          "i"
        ],
        [
          "Κ",
          "κ",
          "kapa",
          "k"
        ],
        [
          "Λ",
          "λ",
          "lamda",
          "l"
        ],
        [
          "Μ",
          "μ",
          "mi",
          "m"
        ],
        [
          "Ν",
          "ν",
          "ni",
          "n"
        ],
        [
          "Ξ",
          "ξ",
          "ksi",
          "ks"
        ],
        [
          "Ο",
          "ο",
          "omikron",
          "o"
        ],
        [
          "Π",
          "π",
          "pi",
          "p"
        ],
        [
          "Ρ",
          "ρ",
          "ro",
          "r"
        ],
        [
          "Σ",
          "σ/ς",
          "sigma",
          "s"
        ],
        [
          "Τ",
          "τ",
          "taf",
          "t"
        ],
        [
          "Υ",
          "υ",
          "ipsilon",
          "i"
        ],
        [
          "Φ",
          "φ",
          "fi",
          "f"
        ],
        [
          "Χ",
          "χ",
          "hi",
          "h"
        ],
        [
          "Ψ",
          "ψ",
          "psi",
          "ps"
        ],
        [
          "Ω",
          "ω",
          "omega",
          "o"
        ]
      ]
    },
    "train": "alpha"
  },
  "a0-u1-t2": {
    "goal": "Tek sesli harfleri ve ikili ünlüleri (δίψηφα) ayırt et; minimal çiftlerle dinle/söyle.",
    "theory": [
      "Tek sesliler: α (a), ε (e), η (i), ι (i), ο (o), υ (i), ω (o). η/ι/υ/ει/οι hepsi /i/ olabilir — yazımı ezberle.",
      "İkililer: αι ≈ e, ει ≈ i, οι ≈ i, ου ≈ u, αυ ≈ av/af, ευ ≈ ev/ef (sonraki sese göre).",
      "Minimal çift: tek ses farkı anlamı değiştirir. είμαι (benim) ≠ είπε (dedi)."
    ],
    "examples": [
      {
        "el": "αι",
        "tr": "e gibi (και = ve)"
      },
      {
        "el": "ει",
        "tr": "i (είμαι)"
      },
      {
        "el": "οι",
        "tr": "i (οι φίλοι)"
      },
      {
        "el": "ου",
        "tr": "u (μου)"
      },
      {
        "el": "αυ",
        "tr": "av/af (αυτοκίνητο)"
      },
      {
        "el": "ευ",
        "tr": "ev/ef (ευχαριστώ)"
      },
      {
        "el": "είμαι",
        "tr": "benim / I am"
      },
      {
        "el": "είπε",
        "tr": "dedi"
      },
      {
        "el": "καλό",
        "tr": "iyi (nötr)"
      },
      {
        "el": "καλή",
        "tr": "iyi (dişil)"
      }
    ],
    "steps": [
      "α ε η ι ο υ ω listesini yüksek sesle 3 kez oku.",
      "αι ει οι ου αυ ευ için her birine 2 örnek kelime yaz.",
      "Minimal çiftleri yavaşça söyle: είμαι/είπε, καλό/καλή, πόλη/πολύ.",
      "Telefonda sesini kaydet; /i/ yazımlarını karıştırıyor musun diye dinle."
    ],
    "practice": [
      "5 ikili için 1’er cümle kur.",
      "Dikte antrenmanından 3 kısa kelime yaz."
    ],
    "check": [
      "αι ile ει farkını örnekle açıklayabiliyor musun?",
      "αυ/ευ’nin av-af / ev-ef değişimini biliyor musun?"
    ],
    "train": "dictation"
  },
  "a0-u1-t3": {
    "goal": "τόνος (vurgu işareti) kuralını anla; yanlış yerde vurgu anlamı bozar.",
    "theory": [
      "Yunanca’da vurgulu ünlünün üstüne τόνος konur: ά έ ή ί ό ύ ώ.",
      "Çoğu kelimede vurgu son üç heceden birindedir. Sözlük/kartta gördüğün aksanı taklit et.",
      "Aynı harf dizisi farklı vurguyla farklı kelime olabilir. Ezberlerken aksanı kelimenin parçası say."
    ],
    "examples": [
      {
        "el": "καλός",
        "tr": "güzel/iyi — vurgu -λός"
      },
      {
        "el": "γάλα",
        "tr": "süt — vurgu γά-"
      },
      {
        "el": "ποτάμι",
        "tr": "nehir"
      },
      {
        "el": "άνθρωπος",
        "tr": "insan"
      },
      {
        "el": "ευχαριστώ",
        "tr": "teşekkürler — son hece"
      }
    ],
    "steps": [
      "Kart destesinden 15 kelime seç; her birinde aksanlı heceyi işaretle.",
      "3 heceli 10 kelimeyi heceleyerek oku: άν-θρω-πος.",
      "Yanlış aksanlı okumayı bilerek dene, sonra doğruyu söyle — kulak alışır."
    ],
    "practice": [
      "Aksansız yazılmış 8 kelimeye τόνος koy (cevap anahtarı: kartın Yunanca yüzü)."
    ],
    "check": [
      "Her yeni kelimeyi aksanıyla mı kaydediyorsun?"
    ]
  },
  "a0-u1-t4": {
    "goal": "İlk 20 temel kelimeyi yüksek sesle akıcı oku; anlamlarını bil.",
    "theory": [
      "Okuma = ses + anlam. Önce yavaş doğru, sonra hız.",
      "Bu liste A0 iletişim için minimumdur. Hepsini Kartlar + Dinle ile pekiştir."
    ],
    "examples": [
      {
        "el": "καλημέρα",
        "tr": "günaydın"
      },
      {
        "el": "καλησπέρα",
        "tr": "iyi akşamlar"
      },
      {
        "el": "καληνύχτα",
        "tr": "iyi geceler"
      },
      {
        "el": "γεια σου",
        "tr": "merhaba (tekil)"
      },
      {
        "el": "αντίο",
        "tr": "hoşça kal"
      },
      {
        "el": "ευχαριστώ",
        "tr": "teşekkürler"
      },
      {
        "el": "παρακαλώ",
        "tr": "lütfen / rica ederim"
      },
      {
        "el": "ναι",
        "tr": "evet"
      },
      {
        "el": "όχι",
        "tr": "hayır"
      },
      {
        "el": "νερό",
        "tr": "su"
      },
      {
        "el": "ψωμί",
        "tr": "ekmek"
      },
      {
        "el": "καφές",
        "tr": "kahve"
      },
      {
        "el": "τυρί",
        "tr": "peynir"
      },
      {
        "el": "σπίτι",
        "tr": "ev"
      },
      {
        "el": "φίλος",
        "tr": "arkadaş"
      },
      {
        "el": "όνομα",
        "tr": "ad"
      },
      {
        "el": "Τουρκία",
        "tr": "Türkiye"
      },
      {
        "el": "Αθήνα",
        "tr": "Atina"
      },
      {
        "el": "μητέρα",
        "tr": "anne"
      },
      {
        "el": "πατέρας",
        "tr": "baba"
      }
    ],
    "steps": [
      "Listeyi 2 kez yavaş oku (aksanlara dikkat).",
      "Telefonuna kaydet; kaydı dinlerken metni takip et.",
      "Türkçe gör → Yunanca söyle (10 kelime karışık).",
      "Kartlar destesini açıp bu kelimeleri işaretle."
    ],
    "practice": [
      "10 kelimelik mini dikte: dinle (TTS) yaz."
    ],
    "check": [
      "20 kelimenin en az 16’sını bir bakışta okuyup anlamını biliyor musun?"
    ],
    "train": "dictation"
  },
  "a0-u2-t1": {
    "goal": "Günün saatine ve yakınlığa göre doğru selamlaşmayı seç.",
    "theory": [
      "καλημέρα: sabah–öğleden sonra erken. καλησπέρα: akşam. καληνύχτα: yatmadan / vedalaşma gecesi.",
      "γεια σου (tekil samimi), γεια σας (çoğul/resmi). αντίο: genel veda.",
      "Cevap olarak da aynı selamı tekrarlayabilirsin: — Καλημέρα! — Καλημέρα!"
    ],
    "examples": [
      {
        "el": "Καλημέρα!",
        "tr": "Günaydın!"
      },
      {
        "el": "Καλησπέρα!",
        "tr": "İyi akşamlar!"
      },
      {
        "el": "Γεια σου!",
        "tr": "Merhaba! (sen)"
      },
      {
        "el": "Γεια σας!",
        "tr": "Merhaba! (siz)"
      },
      {
        "el": "Αντίο!",
        "tr": "Hoşça kal!"
      },
      {
        "el": "Τα λέμε!",
        "tr": "Görüşürüz!"
      }
    ],
    "steps": [
      "6 durumu yaz: sabah komşu, akşam patron, gece aile, arkadaş sokakta… hangisi?",
      "Her selamı 5 kez yüksek sesle tekrarla.",
      "Günün kalıbı kartına dokunup dinle."
    ],
    "practice": [
      "Rol: A selamlar, B uygun yanıt verir — 6 tur."
    ],
    "check": [
      "καλημέρα / καλησπέρα / καληνύχτα ayırabiliyor musun?"
    ]
  },
  "a0-u2-t2": {
    "goal": "Ad, memnuniyet ve nereli olduğunu sorup cevaplayabilmek.",
    "theory": [
      "Με λένε + ad. Χαίρω πολύ = memnun oldum. Από πού είσαι; = Nerelisin?",
      "Είμαι από την Τουρκία / από την Αθήνα. Ülke/şehirde maddeye dikkat (την).",
      "Kısa diyalog ezberi: selam → ad → memnuniyet → nereli → veda."
    ],
    "examples": [
      {
        "el": "Με λένε Νίκο.",
        "tr": "Adım Nikos."
      },
      {
        "el": "Χαίρω πολύ.",
        "tr": "Memnun oldum."
      },
      {
        "el": "Από πού είσαι;",
        "tr": "Nerelisin?"
      },
      {
        "el": "Είμαι από την Τουρκία.",
        "tr": "Türkiye’denim."
      },
      {
        "el": "Πώς σε λένε;",
        "tr": "Adın ne?"
      }
    ],
    "steps": [
      "Diyaloğu ezberle ve iki rolü de oyna (kaydet).",
      "Kendi adın ve şehrinle yeniden yaz.",
      "Kartlar → Diyalog antrenmanına gir."
    ],
    "practice": [
      "Partner yoksa: soruları yaz, cevapları sesli ver."
    ],
    "check": [
      "30 saniyelik tanışma diyaloğunu ezberden kurabiliyor musun?"
    ],
    "train": "dialogue"
  },
  "a0-u2-t3": {
    "goal": "0–100 sayılarını tanı; yaş, fiyat ve saat için kullan.",
    "theory": [
      "0–20 ayrı ezber; 30,40…90 kalıp; 21=είκοσι ένα. 100=εκατό.",
      "Yaş: Είμαι είκοσι πέντε (χρονών). Fiyat: Κάνει δέκα ευρώ.",
      "Uygulamada Sayı + 100+ antrenmanları var — buradan çıkma."
    ],
    "examples": [
      {
        "el": "μηδέν",
        "tr": "0"
      },
      {
        "el": "ένα",
        "tr": "1"
      },
      {
        "el": "δύο",
        "tr": "2"
      },
      {
        "el": "τρία",
        "tr": "3"
      },
      {
        "el": "τέσσερα",
        "tr": "4"
      },
      {
        "el": "πέντε",
        "tr": "5"
      },
      {
        "el": "έξι",
        "tr": "6"
      },
      {
        "el": "επτά",
        "tr": "7"
      },
      {
        "el": "οκτώ",
        "tr": "8"
      },
      {
        "el": "εννέα",
        "tr": "9"
      },
      {
        "el": "δέκα",
        "tr": "10"
      },
      {
        "el": "είκοσι",
        "tr": "20"
      },
      {
        "el": "τριάντα",
        "tr": "30"
      },
      {
        "el": "πενήντα",
        "tr": "50"
      },
      {
        "el": "εκατό",
        "tr": "100"
      },
      {
        "el": "Είμαι είκοσι δύο.",
        "tr": "22 yaşındayım."
      }
    ],
    "steps": [
      "0–20’yi sırayla yaz ve söyle.",
      "15 rastgele sayı üret (veya zar); Yunancasını söyle.",
      "Antrenman: Sayı + Büyük sayı (100+)."
    ],
    "practice": [
      "Yaşını ve 3 fiyat cümlesi söyle."
    ],
    "check": [
      "0–100 arasından rastgele 10 sayıyı hatasız söyleyebiliyor musun?"
    ],
    "train": "number"
  },
  "a0-u2-t4": {
    "goal": "1 dakikalık öz tanıtımı kaydet; hataları not et.",
    "theory": [
      "Kontrol görevi: öğrenilenleri tek parçada birleştir.",
      "Şablon: Selam + ad + nereli + yaş + 1 ek cümle + veda."
    ],
    "examples": [
      {
        "el": "Καλημέρα! Με λένε…",
        "tr": "Günaydın, adım…"
      },
      {
        "el": "Είμαι από την Τουρκία.",
        "tr": "Türkiye’denim."
      },
      {
        "el": "Είμαι … χρονών.",
        "tr": "… yaşındayım."
      },
      {
        "el": "Μένω στην…",
        "tr": "…’de yaşıyorum."
      },
      {
        "el": "Αντίο!",
        "tr": "Hoşça kal!"
      }
    ],
    "steps": [
      "Metni yaz (6–8 cümle), sonra ezbere kaydet.",
      "Kaydı dinle: aksan, sayı, madde hatalarını listele.",
      "Aynı kaydı 1 kez daha düzeltip çek."
    ],
    "practice": [
      "Hata günlüğüne 3 madde yaz (İlerleme)."
    ],
    "check": [
      "Kayda bakmadan akıcı 45–60 sn konuşabiliyor musun?"
    ]
  },
  "a0-u3-t1": {
    "goal": "50 kelimeyi aksanlı ve anlaşılır okumak.",
    "theory": [
      "Hız değil doğruluk. Her kelimede τόνος’a bak.",
      "Kartlar ekranındaki destelerden oku; bilmediğini Leitner’de bırak."
    ],
    "examples": [
      {
        "el": "επανάληψη",
        "tr": "tekrar"
      },
      {
        "el": "προφορά",
        "tr": "telaffuz"
      }
    ],
    "steps": [
      "A0/A1 destesinden 50 kart aç.",
      "Her kelimeyi 2 kez söyle; 10’da bir kaydet.",
      "Zor 10’u ayrı listele, yarın tekrar."
    ],
    "practice": [
      "Alfabe antrenmanı 1 tur + 20 kart."
    ],
    "check": [
      "50’nin en az 40’ını aksanlı okudun mu?"
    ]
  },
  "a0-u3-t2": {
    "goal": "Minimal çiftlerde ses farkını duymak ve üretmek.",
    "theory": [
      "πόλη (şehir) / πολύ (çok); καλό / καλώ (çağırmak); φίλος / φύλλο (yaprak).",
      "Önce dinle (TTS), sonra yan yana söyle."
    ],
    "examples": [
      {
        "el": "πόλη",
        "tr": "şehir"
      },
      {
        "el": "πολύ",
        "tr": "çok"
      },
      {
        "el": "καλό",
        "tr": "iyi"
      },
      {
        "el": "καλώ",
        "tr": "çağırmak"
      },
      {
        "el": "φίλος",
        "tr": "arkadaş"
      },
      {
        "el": "φύλλο",
        "tr": "yaprak"
      }
    ],
    "steps": [
      "Her çifti 5 kez yavaş oku.",
      "Birini söyle, kaydı dinleyip hangisi olduğunu yaz.",
      "Dinle-anla antrenmanına gir."
    ],
    "practice": [
      "6 kelimeyi karışık dikte et."
    ],
    "check": [
      "Üç çiftin farkını başkasına anlatabilecek kadar net misin?"
    ],
    "train": "listen"
  },
  "a0-u3-t3": {
    "goal": "El yazısıyla alfabe ve 20 kelime; motor bellek.",
    "theory": [
      "Ekran yeterli değil: el yazısı harf biçimini oturtur.",
      "ς sonunu unutma; α/ο karışıklığına dikkat."
    ],
    "examples": [
      {
        "el": "Γράφω στο τετράδιο.",
        "tr": "Deftere yazıyorum."
      }
    ],
    "steps": [
      "1 sayfa: Αα–Ωω.",
      "20 kelime (önceki listeden) 2’şer kez yaz.",
      "En çirkin 5 harfi satır boyunca tekrarla."
    ],
    "practice": [
      "Fotoğraf çekip yarın kendin kontrol et."
    ],
    "check": [
      "Büyük/küçük karışık yazınca okunaklı mı?"
    ]
  },
  "a1-u1-t1": {
    "goal": "İsim cinsiyetini ve ο/η/το maddesini kelimeyle birlikte ezberlemek.",
    "theory": [
      "Yunanca isimler eril (ο), dişil (η) veya nötr (το). Madde ismin kimliğidir — kelimeyi maddesiz ezberleme.",
      "Sık kalıplar: eril -ος/-ας/-ης (ο φίλος, ο άντρας, ο μαθητής); dişil -α/-η (η γυναίκα, η πόλη); nötr -ο/-ι/-μα (το βιβλίο, το παιδί, το πρόβλημα).",
      "İstisnalar vardır; gördüğün maddeyi doğru kabul et."
    ],
    "examples": [
      {
        "el": "ο άντρας",
        "tr": "adam"
      },
      {
        "el": "η γυναίκα",
        "tr": "kadın"
      },
      {
        "el": "το παιδί",
        "tr": "çocuk"
      },
      {
        "el": "ο καφές",
        "tr": "kahve"
      },
      {
        "el": "η πόλη",
        "tr": "şehir"
      },
      {
        "el": "το σπίτι",
        "tr": "ev"
      },
      {
        "el": "η μέρα",
        "tr": "gün"
      },
      {
        "el": "το νερό",
        "tr": "su"
      }
    ],
    "steps": [
      "30 isim listesi çıkar: madde + isim + Türkçe.",
      "Antrenman: Madde (gender) — en az 15 tur.",
      "Yanlışları hata günlüğüne yaz."
    ],
    "practice": [
      "Her cinsten 5’er ismi ezbere maddeyle söyle."
    ],
    "check": [
      "Rastgele isimde ο/η/το’yu %90 doğru seçebiliyor musun?"
    ],
    "train": "gender"
  },
  "a1-u1-t2": {
    "goal": "Tekilden çoğula geçiş: οι / οι / τα ve sık çoğul kalıpları.",
    "theory": [
      "Maddeler: ο → οι, η → οι, το → τα.",
      "Örnekler: ο άντρας → οι άντρες; η γυναίκα → οι γυναίκες; το παιδί → τα παιδιά; το βιβλίο → τα βιβλία.",
      "Çoğul ekleri isim sınıfına göre değişir; ezber + antrenman."
    ],
    "examples": [
      {
        "el": "οι άντρες",
        "tr": "adamlar"
      },
      {
        "el": "οι γυναίκες",
        "tr": "kadınlar"
      },
      {
        "el": "τα παιδιά",
        "tr": "çocuklar"
      },
      {
        "el": "τα βιβλία",
        "tr": "kitaplar"
      },
      {
        "el": "οι φίλοι",
        "tr": "arkadaşlar"
      },
      {
        "el": "οι πόλεις",
        "tr": "şehirler"
      }
    ],
    "steps": [
      "20 ismin çoğulunu yaz (maddeyle).",
      "Antrenman: Çoğul.",
      "Kartlarda çoğul formları not et."
    ],
    "practice": [
      "10 tekil ver → çoğul söyle."
    ],
    "check": [
      "οι / τα seçimini karıştırmıyor musun?"
    ],
    "train": "plural"
  },
  "a1-u1-t3": {
    "goal": "Belirsiz madde ένας / μία / ένα ile istek ve tanıtım cümleleri.",
    "theory": [
      "Belirli: ο/η/το. Belirsiz: ένας (eril), μία/μια (dişil), ένα (nötr).",
      "Nesne halinde sık: έναν καφέ, μία μπύρα, ένα νερό.",
      "Θέλω έναν καφέ. / Έχω ένα αδέρφι."
    ],
    "examples": [
      {
        "el": "ένας άντρας",
        "tr": "bir adam"
      },
      {
        "el": "μία γυναίκα",
        "tr": "bir kadın"
      },
      {
        "el": "ένα παιδί",
        "tr": "bir çocuk"
      },
      {
        "el": "Θέλω έναν καφέ.",
        "tr": "Bir kahve istiyorum."
      },
      {
        "el": "Έχω μία ιδέα.",
        "tr": "Bir fikrim var."
      }
    ],
    "steps": [
      "10 sipariş cümlesi yaz (έναν/μία/ένα).",
      "Kafe diyaloğunda kullan.",
      "Scramble: cümle kur."
    ],
    "practice": [
      "5 nesneyi belirsiz maddeyle söyle."
    ],
    "check": [
      "έναν ile ένα farkını örnekle açıklayabiliyor musun?"
    ],
    "train": "scramble"
  },
  "a1-u2-t1": {
    "goal": "είμαι çekimini ve olumsuzunu (δεν είμαι) otomatikleştirmek.",
    "theory": [
      "είμαι, είσαι, είναι, είμαστε, είστε, είναι.",
      "Olumsuz: δεν + fiil → Δεν είμαι γιατρός.",
      "Tanımlama: Είμαι φοιτητής. Yer: Είμαι στην Αθήνα."
    ],
    "examples": [
      {
        "el": "Είμαι από την Τουρκία.",
        "tr": "Türkiye’denim."
      },
      {
        "el": "Είσαι καλά;",
        "tr": "İyi misin?"
      },
      {
        "el": "Είναι δάσκαλος.",
        "tr": "O öğretmen."
      },
      {
        "el": "Δεν είμαι κουρασμένος.",
        "tr": "Yorgun değilim."
      },
      {
        "el": "Είμαστε φίλοι.",
        "tr": "Arkadaşız."
      }
    ],
    "steps": [
      "Tabloyu ezberle, boşluk doldur.",
      "12 cümle: 6 olumlu 6 olumsuz.",
      "Fiil antrenmanı."
    ],
    "practice": [
      "6 kişiyi karışık sor → çekim söyle."
    ],
    "check": [
      "είναι’nin hem o hem onlar için olduğunu unutmuyor musun?"
    ],
    "train": "verb"
  },
  "a1-u2-t2": {
    "goal": "έχω çekimi + sahiplik / ilişki cümleleri.",
    "theory": [
      "έχω, έχεις, έχει, έχουμε, έχετε, έχουν.",
      "Έχω δύο αδέρφια. Έχει χρόνο; Δεν έχω χρήματα."
    ],
    "examples": [
      {
        "el": "Έχω ένα αυτοκίνητο.",
        "tr": "Bir arabam var."
      },
      {
        "el": "Έχεις αδέρφια;",
        "tr": "Kardeşlerin var mı?"
      },
      {
        "el": "Δεν έχω χρόνο.",
        "tr": "Zamanım yok."
      },
      {
        "el": "Έχουμε μάθημα.",
        "tr": "Dersimiz var."
      }
    ],
    "steps": [
      "15 cümle yaz (sahip ol / olmamak).",
      "Tanışma metnine έχω ekle."
    ],
    "practice": [
      "Aileni έχω ile anlat (5 cümle)."
    ],
    "check": [
      "Çekimi ezbere yazabiliyor musun?"
    ]
  },
  "a1-u2-t3": {
    "goal": "80–100 kelimelik Yunanca profil metni yazıp sesli okumak.",
    "theory": [
      "İçerik: ad, yaş, şehir, iş/okul, aile, hobiler, neden Yunanca.",
      "Sadece είμαι/έχω/şimdiki zaman basit cümleler yeterli."
    ],
    "examples": [
      {
        "el": "Με λένε… και μένω στην…",
        "tr": "Adım… ve …’de yaşıyorum."
      },
      {
        "el": "Μου αρέσει ο καφές και τα βιβλία.",
        "tr": "Kahve ve kitapları severim."
      }
    ],
    "steps": [
      "Taslak Türkçe 5 madde → Yunanca yaz.",
      "Sesli oku, kaydet.",
      "Yazma antrenmanı promptunu da yap."
    ],
    "practice": [
      "Metni başkası anlamadan düzgün okuyabiliyor musun?"
    ],
    "check": [
      "En az 80 kelime ve 3 διαφορετικό yapı var mı?"
    ],
    "train": "write"
  },
  "a1-u3-t1": {
    "goal": "A tipi -ω fiillerin şimdiki zaman çekimi.",
    "theory": [
      "γράφω: γράφω, γράφεις, γράφει, γράφουμε, γράφετε, γράφουν.",
      "Sık fiiller: διαβάζω, πίνω, τρώω, δουλεύω, μαθαίνω, καταλαβαίνω.",
      "Konuşma dili: μιλάω / μιλάς… da duyulur."
    ],
    "examples": [
      {
        "el": "Γράφω ένα μήνυμα.",
        "tr": "Mesaj yazıyorum."
      },
      {
        "el": "Διαβάζω ελληνικά.",
        "tr": "Yunanca okuyorum."
      },
      {
        "el": "Πίνω καφέ.",
        "tr": "Kahve içiyorum."
      },
      {
        "el": "Καταλαβαίνω λίγο.",
        "tr": "Biraz anlıyorum."
      }
    ],
    "steps": [
      "5 fiilin tam çekim tablosunu yaz.",
      "Günlük 8 cümle kur.",
      "Fiil antrenmanı."
    ],
    "practice": [
      "γράφω’yu 6 kişi için hatasız söyle."
    ],
    "check": [
      "-ω fiillerde kişi eklerini ezberledin mi?"
    ],
    "train": "verb"
  },
  "a1-u3-t2": {
    "goal": "B tipi -άω/-ώ fiilleri A tipiyle karıştırmadan çekmek.",
    "theory": [
      "αγαπώ/αγαπάω: αγαπώ, αγαπάς, αγαπά, αγαπάμε, αγαπάτε, αγαπούν.",
      "ρωτάω, περπατάω, κοιτάω, βοηθάω sık B tipi.",
      "A ile B’yi aynı listede karıştırarak test et."
    ],
    "examples": [
      {
        "el": "Αγαπάω την Ελλάδα.",
        "tr": "Yunanistan’ı seviyorum."
      },
      {
        "el": "Ρωτάω τον δάσκαλο.",
        "tr": "Öğretmene soruyorum."
      },
      {
        "el": "Περπατάω κάθε μέρα.",
        "tr": "Her gün yürüyorum."
      }
    ],
    "steps": [
      "10 B tipi fiil listesi + 2’şer cümle.",
      "A/B karışık 10 soruluk mini test kendine yap."
    ],
    "practice": [
      "αγαπάω çekimini yaz."
    ],
    "check": [
      "A tipi ile B tipi eki farkını söyleyebiliyor musun?"
    ]
  },
  "a1-u3-t3": {
    "goal": "Sabah–akşam rutini şimdiki zamanda anlatmak (12+ cümle).",
    "theory": [
      "Sıklık: πάντα, συχνά, συνήθως, μετά, μετά το μάθημα…",
      "Fiilleri zincirle: Ξυπνάω → πλένομαι → πίνω καφέ → πάω στη δουλειά."
    ],
    "examples": [
      {
        "el": "Το πρωί ξυπνάω στις επτά.",
        "tr": "Sabah yedide uyanırım."
      },
      {
        "el": "Μετά πίνω καφέ και διαβάζω.",
        "tr": "Sonra kahve içer ve okurum."
      },
      {
        "el": "Το βράδυ βλέπω μια σειρά.",
        "tr": "Akşam bir dizi izlerim."
      }
    ],
    "steps": [
      "12 cümle yaz, sonra ezbere söyle.",
      "Sıklık antrenmanı.",
      "Kaydet."
    ],
    "practice": [
      "Zaman sırası bozulmadan anlatabiliyor musun?"
    ],
    "check": [
      "En az 12 cümle ve 3 sıklık zarfı var mı?"
    ],
    "train": "frequency"
  },
  "a1-u3-t4": {
    "goal": "Yavaş diyalogları uygulama içinde dinleyip ana fikri çıkarmak.",
    "theory": [
      "Dış kaynak yok: Dinle-anla + Diyalog + TTS ile çalış.",
      "İlk geçişte genel fikir; ikinci geçişte kim/ne/nerede."
    ],
    "examples": [
      {
        "el": "Τι είπε;",
        "tr": "Ne dedi?"
      },
      {
        "el": "Πού είναι;",
        "tr": "Nerede?"
      }
    ],
    "steps": [
      "Dinle-anla antrenmanı 2 tur.",
      "Diyalog 1 tur.",
      "Her diyalog için Türkçe 1 cümle özet."
    ],
    "practice": [
      "3 diyalog özeti yaz."
    ],
    "check": [
      "Ana fikri kaçırmadan özetleyebiliyor musun?"
    ],
    "train": "listen"
  },
  "a1-u4-t1": {
    "goal": "Kafede sipariş, hesap ve nazik istek kalıpları.",
    "theory": [
      "Θα ήθελα… / Έναν καφέ, παρακαλώ. Τον λογαριασμό, παρακαλώ.",
      "Είναι πικάντικο; Έχετε χορτοφαγικό; Για πακέτο;"
    ],
    "examples": [
      {
        "el": "Θα ήθελα έναν καφέ χωρίς ζάχαρη.",
        "tr": "Şekersiz kahve isterdim."
      },
      {
        "el": "Τον λογαριασμό, παρακαλώ.",
        "tr": "Hesap lütfen."
      },
      {
        "el": "Τι προτείνετε;",
        "tr": "Ne önerirsiniz?"
      }
    ],
    "steps": [
      "Restoran antrenmanı.",
      "Nazik üslup antrenmanı.",
      "Rol kaydı: garson + müşteri."
    ],
    "practice": [
      "Sipariş→hesap diyaloğunu ezbere kur."
    ],
    "check": [
      "5 kalıbı hatasız kullanabiliyor musun?"
    ],
    "train": "restaurant"
  },
  "a1-u4-t2": {
    "goal": "Alışveriş kelimeleri: fiyat, beden, renk, ucuz/pahalı.",
    "theory": [
      "Πόσο κάνει; Φτηνό / ακριβό. Μέγεθος, χρώμα, έκπτωση, ταμείο, απόδειξη."
    ],
    "examples": [
      {
        "el": "Πόσο κάνει;",
        "tr": "Kaç para?"
      },
      {
        "el": "Είναι ακριβό.",
        "tr": "Pahalı."
      },
      {
        "el": "Έχετε μεγαλύτερο μέγεθος;",
        "tr": "Daha büyük beden var mı?"
      }
    ],
    "steps": [
      "Kartlar: Alışveriş + Renkler desteleri.",
      "25 kelimeyi maddeyle yaz.",
      "Eşleştir oyunu."
    ],
    "practice": [
      "10 kelime TR→EL."
    ],
    "check": [
      "Fiyat sorma cümlesi otomatik mi?"
    ],
    "train": "match"
  },
  "a1-u4-t3": {
    "goal": "Yön sorma ve tarif kalıpları.",
    "theory": [
      "Πού είναι…; Πώς πάω στο/στην…;",
      "δεξιά, αριστερά, ευθεία, κοντά, μακριά, απέναντι, δίπλα, στη γωνία."
    ],
    "examples": [
      {
        "el": "Πού είναι η στάση;",
        "tr": "Durak nerede?"
      },
      {
        "el": "Στρίψε δεξιά.",
        "tr": "Sağa dön."
      },
      {
        "el": "Είναι κοντά.",
        "tr": "Yakın."
      }
    ],
    "steps": [
      "Yön antrenmanı.",
      "Ulaşım kelimeleri.",
      "Hayali haritada 5 tarif söyle."
    ],
    "practice": [
      "3 soru + 3 tarif yaz."
    ],
    "check": [
      "Sağ/sol/düz karışmıyor mu?"
    ],
    "train": "direction"
  },
  "a1-u4-t4": {
    "goal": "A1 kapı: madde, είμαι/έχω, şimdiki zaman, kelime — öz test.",
    "theory": [
      "Hedef ≥ %80. Uygulama: Mini sınav + Hızlı 10 + Yanlış tekrarı.",
      "Zayıf türü not et; o antrenmana dön."
    ],
    "examples": [
      {
        "el": "Πόσο καλά;",
        "tr": "Ne kadar iyi?"
      }
    ],
    "steps": [
      "Mini sınav (20).",
      "Hızlı 10.",
      "Yanlış tekrarını bitir."
    ],
    "practice": [
      "Skoru İlerleme notuna yaz."
    ],
    "check": [
      "%80+ veya zayıf konu listesi hazır mı?"
    ],
    "train": "exam"
  },
  "a1-u5-t1": {
    "goal": "Kişi zamirleri: εγώ εσύ αυτός/αυτή/αυτό…",
    "theory": [
      "Özne zamirleri çoğu zaman düşer (fiil eki yeter); vurgu/karşıtlıkta kullanılır.",
      "Εγώ είμαι… Εσύ; Αυτός είναι…"
    ],
    "examples": [
      {
        "el": "Εγώ είμαι φοιτητής.",
        "tr": "Ben öğrenciyim."
      },
      {
        "el": "Εσύ τι κάνεις;",
        "tr": "Sen ne yapıyorsun?"
      },
      {
        "el": "Αυτοί είναι φίλοι μου.",
        "tr": "Onlar arkadaşlarım."
      }
    ],
    "steps": [
      "Tablo ezber + 12 cümle.",
      "Zamir antrenmanı."
    ],
    "practice": [
      "6 zamiri örnek cümlede kullan."
    ],
    "check": [
      "αυτός/αυτή/αυτό cinsiyet uyumuna dikkat ettin mi?"
    ],
    "train": "pronoun"
  },
  "a1-u5-t2": {
    "goal": "Soru sözcükleriyle mini röportaj.",
    "theory": [
      "τι, ποιος/ποια, πού, πότε, γιατί, πώς, πόσο, πόσοι…",
      "Cevapta tam cümle kullan."
    ],
    "examples": [
      {
        "el": "Τι κάνεις;",
        "tr": "Ne yapıyorsun?"
      },
      {
        "el": "Πού μένεις;",
        "tr": "Nerede yaşıyorsun?"
      },
      {
        "el": "Πότε φεύγεις;",
        "tr": "Ne zaman gidiyorsun?"
      },
      {
        "el": "Γιατί μαθαίνεις ελληνικά;",
        "tr": "Neden Yunanca öğreniyorsun?"
      }
    ],
    "steps": [
      "Soru antrenmanı.",
      "10 soru yaz, kendi cevapla, kaydet."
    ],
    "practice": [
      "Röportaj: 6 soru 6 cevap."
    ],
    "check": [
      "Soru sözcüğünü yanlış seçmiyor musun?"
    ],
    "train": "question"
  },
  "a1-u5-t3": {
    "goal": "İyelik: μου σου του της… Το βιβλίο μου.",
    "theory": [
      "μου/σου/του/της/μας/σας/τους isimden sonra (veya özel yapılarda önce).",
      "Το όνομά μου. Η φίλη σου. Το σπίτι τους."
    ],
    "examples": [
      {
        "el": "Το βιβλίο μου.",
        "tr": "Kitabım."
      },
      {
        "el": "Η αδελφή σου.",
        "tr": "Kız kardeşin."
      },
      {
        "el": "Το αυτοκίνητό του.",
        "tr": "Onun arabası."
      }
    ],
    "steps": [
      "15 iyelik cümlesi yaz.",
      "Genitif antrenmanı ile sahiplik pekiştir."
    ],
    "practice": [
      "Aile üyelerini iyelikle anlat."
    ],
    "check": [
      "μου/σου yerini doğru koyuyor musun?"
    ],
    "train": "genitive"
  },
  "a1-u6-t1": {
    "goal": "Haftanın günlerini ezberleyip cümlede kullanmak.",
    "theory": [
      "Δευτέρα Τρίτη Τετάρτη Πέμπτη Παρασκευή Σάββατο Κυριακή.",
      "την Δευτέρα = pazartesi günü."
    ],
    "examples": [
      {
        "el": "τη Δευτέρα",
        "tr": "pazartesi"
      },
      {
        "el": "το Σάββατο",
        "tr": "cumartesi"
      },
      {
        "el": "Έχω μάθημα την Τρίτη.",
        "tr": "Salı dersim var."
      }
    ],
    "steps": [
      "Gün antrenmanı.",
      "7 cümle: her gün için bir aktivite."
    ],
    "practice": [
      "Karışık sor: Bugün ne? Yarın ne?"
    ],
    "check": [
      "7 günü sırasız sayabiliyor musun?"
    ],
    "train": "weekdays"
  },
  "a1-u6-t2": {
    "goal": "Sıklık zarflarıyla rutin anlatmak.",
    "theory": [
      "πάντα, συνήθως, συχνά, μερικές φορές, σπάνια, ποτέ.",
      "Olumsuzda ποτέ ile Δεν birlikte: Δεν πάω ποτέ."
    ],
    "examples": [
      {
        "el": "Πάντα πίνω καφέ.",
        "tr": "Her zaman kahve içerim."
      },
      {
        "el": "Σπάνια βλέπω τηλεόραση.",
        "tr": "Nadiren TV izlerim."
      },
      {
        "el": "Δεν καπνίζω ποτέ.",
        "tr": "Asla sigara içmem."
      }
    ],
    "steps": [
      "Sıklık antrenmanı.",
      "Rutinini 8 cümlede anlat."
    ],
    "practice": [
      "6 zarfı örnekle."
    ],
    "check": [
      "ποτέ + δεν kuralını uyguluyor musun?"
    ],
    "train": "frequency"
  },
  "a1-u6-t3": {
    "goal": "Saat sorma ve söyleme.",
    "theory": [
      "Τι ώρα είναι; Είναι τρεις. Είναι και τέταρτο / παρά τέταρτο / και μισή."
    ],
    "examples": [
      {
        "el": "Τι ώρα είναι;",
        "tr": "Saat kaç?"
      },
      {
        "el": "Είναι δύο.",
        "tr": "Saat iki."
      },
      {
        "el": "Στις οκτώ.",
        "tr": "Sekizde."
      }
    ],
    "steps": [
      "Saat antrenmanı.",
      "Günün programını saatlerle söyle."
    ],
    "practice": [
      "10 rastgele saat söyle."
    ],
    "check": [
      "και μισή / παρά ayrımını biliyor musun?"
    ],
    "train": "time"
  },
  "a2-u1-t1": {
    "goal": "Düzenli aorist: tamamlanmış geçmiş + augment (έ-).",
    "theory": [
      "Aorist = bir kez / bitmiş olay. έγραψα, διάβασα, μίλησα.",
      "Çoğu fiilde geçmişte έ- gelir (augment). Vurgu kurallarına karttan bak.",
      "Şimdiki γράφω → aorist έγραψα (ben)."
    ],
    "examples": [
      {
        "el": "Χθες έγραψα ένα μήνυμα.",
        "tr": "Dün bir mesaj yazdım."
      },
      {
        "el": "Διάβασα το βιβλίο.",
        "tr": "Kitabı okudum."
      },
      {
        "el": "Μίλησα με τον Νίκο.",
        "tr": "Nikos’la konuştum."
      }
    ],
    "steps": [
      "15 fiilin aorist (εγώ) formunu yaz.",
      "Aorist antrenmanı.",
      "Aspect: aorist seç."
    ],
    "practice": [
      "10 geçmiş cümle (hepsi aorist)."
    ],
    "check": [
      "Augment’i unutmuyor musun?"
    ],
    "train": "aorist"
  },
  "a2-u1-t2": {
    "goal": "Düzensiz aoristleri kart+cümleyle sabitlemek.",
    "theory": [
      "πήγα, ήρθα, είδα, είπα, έφαγα, ήπια, πήρα, έδωσα, βγήκα, μπήκα…",
      "Bunlar yüksek frekans — ayrı liste şart."
    ],
    "examples": [
      {
        "el": "Πήγα στην Αθήνα.",
        "tr": "Atina’ya gittim."
      },
      {
        "el": "Είδα μια ταινία.",
        "tr": "Bir film gördüm."
      },
      {
        "el": "Είπα την αλήθεια.",
        "tr": "Gerçeği söyledim."
      },
      {
        "el": "Ήρθα νωρίς.",
        "tr": "Erken geldim."
      }
    ],
    "steps": [
      "Düzensiz aorist antrenmanı.",
      "Her fiile 2 cümle.",
      "Hızlı 5’te aorist gelsin."
    ],
    "practice": [
      "8 düzensizi TR→EL söyle."
    ],
    "check": [
      "πήγα/ήρθα/είδα otomatik mi?"
    ],
    "train": "aorist"
  },
  "a2-u1-t3": {
    "goal": "Aorist ile «dün» günlüğü (≈150 kelime) yazıp okumak.",
    "theory": [
      "Sadece bitmiş olaylar. Saat + yer + kim ile zenginleştir.",
      "Imperfect’e kayma."
    ],
    "examples": [
      {
        "el": "Χθες το πρωί…",
        "tr": "Dün sabah…"
      },
      {
        "el": "Μετά πήγα…",
        "tr": "Sonra gittim…"
      }
    ],
    "steps": [
      "150 kelime yaz.",
      "Sesli oku.",
      "3 aorist hatasını düzelt."
    ],
    "practice": [
      "Metinde en az 12 aorist var mı?"
    ],
    "check": [
      "Okurken aksan ve kişi ekleri doğru mu?"
    ]
  },
  "a2-u2-t1": {
    "goal": "Παρατατικός: süre, alışkanlık, arka plan.",
    "theory": [
      "έγραφα = yazıyordum / yazardım. Aorist έγραψα = yazdım (bitirdim).",
      "Παλιά διάβαζα πολύ. Χθες διάβασα ένα κεφάλαιο."
    ],
    "examples": [
      {
        "el": "Όταν ήμουν μικρός, έπαιζα ποδόσφαιρο.",
        "tr": "Küçükken futbol oynardım."
      },
      {
        "el": "Χθες έβλεπα τηλεόραση όταν…",
        "tr": "Dün TV izliyordum ki…"
      }
    ],
    "steps": [
      "Aspect antrenmanı.",
      "10 çift cümle: aorist vs imperfect."
    ],
    "practice": [
      "Farkı Türkçe açıkla + 2 örnek."
    ],
    "check": [
      "Alışkanlık için imperfect seçiyor musun?"
    ],
    "train": "aspect"
  },
  "a2-u2-t2": {
    "goal": "Çocukluk anlatısı (120+ kelime, παρατατικός ağırlıklı).",
    "theory": [
      "Mekan, alışkanlıklar, duygular. Ara sıra aorist ile tek olay ekle."
    ],
    "examples": [
      {
        "el": "Πήγαινα στο σχολείο με τα πόδια.",
        "tr": "Okula yürüyerek giderdim."
      }
    ],
    "steps": [
      "120 kelime yaz.",
      "Imperfect fiilleri altını çiz.",
      "Sesli oku."
    ],
    "practice": [
      "Alışkanlık cümleleri net mi?"
    ],
    "check": [
      "120+ kelime tamam mı?"
    ]
  },
  "a2-u2-t3": {
    "goal": "10 cümlede aorist/imperfect seçimi + gerekçe.",
    "theory": [
      "Her cümlede sor: bitmiş tek olay mı, süre/alışkanlık mı?"
    ],
    "examples": [
      {
        "el": "Χθες είδα τον Γιάννη.",
        "tr": "Aorist — tek olay"
      },
      {
        "el": "Κάθε μέρα έβλεπα τον Γιάννη.",
        "tr": "Imperfect — alışkanlık"
      }
    ],
    "steps": [
      "10 cümle yaz, yanına A veya I koy.",
      "Aspect antrenmanı 2 tur."
    ],
    "practice": [
      "Gerekçeleri Türkçe birer satır."
    ],
    "check": [
      "10/10 gerekçe mantıklı mı?"
    ],
    "train": "aspect"
  },
  "a2-u3-t1": {
    "goal": "Θα + fiil ile basit gelecek planları.",
    "theory": [
      "Θα πάω, θα δω, θα μιλήσω. Olumsuz: Δεν θα…",
      "Yakın plan ve tahmin."
    ],
    "examples": [
      {
        "el": "Αύριο θα πάω στη δουλειά.",
        "tr": "Yarın işe gideceğim."
      },
      {
        "el": "Δεν θα αργήσω.",
        "tr": "Gecikmeyeceğim."
      }
    ],
    "steps": [
      "20 plan cümlesi.",
      "θα/να/ας antrenmanı.",
      "Haftalık takvimini söyle."
    ],
    "practice": [
      "10 gelecek cümle kaydet."
    ],
    "check": [
      "Θα’yı unutmuyor musun?"
    ],
    "train": "particle"
  },
  "a2-u3-t2": {
    "goal": "Cumartesi–Pazar programını yazılı ve sözlü anlatmak.",
    "theory": [
      "Gelecek + saat + yer. Bağlaç: και, μετά, το βράδυ."
    ],
    "examples": [
      {
        "el": "Το Σάββατο θα…",
        "tr": "Cumartesi …acağım."
      }
    ],
    "steps": [
      "Yaz 10 cümle → ezbere 1 dk konuş.",
      "Gün + saat antrenmanı."
    ],
    "practice": [
      "Plan gerçekçi ve çeşitli mi?"
    ],
    "check": [
      "Sözlüde takılmadan bitirdin mi?"
    ]
  },
  "a2-u3-t3": {
    "goal": "Nazik istek: Θα ήθελα, μπορώ να…, μήπως…",
    "theory": [
      "Emir yerine rica. Restoran, ofis, yardım isteme."
    ],
    "examples": [
      {
        "el": "Θα ήθελα ένα νερό.",
        "tr": "Bir su isterdim."
      },
      {
        "el": "Μπορώ να κλείσω την πόρτα;",
        "tr": "Kapıyı kapatabilir miyim?"
      },
      {
        "el": "Μήπως θα μπορούσατε να βοηθήσετε;",
        "tr": "Yardım edebilir misiniz?"
      }
    ],
    "steps": [
      "Nazik üslup antrenmanı.",
      "8 rica cümlesi.",
      "Polite + restaurant."
    ],
    "practice": [
      "Resmi bir ricayı kaydet."
    ],
    "check": [
      "Kaba emir kullanmadan çözebiliyor musun?"
    ],
    "train": "polite"
  },
  "a2-u4-t1": {
    "goal": "Temel bağlaçlar: και αλλά γιατί όταν αν…",
    "theory": [
      "Cümleleri birleştir; YDS ve yazma için temel.",
      "ωστόσο, γι' αυτό, δηλαδή ekle."
    ],
    "examples": [
      {
        "el": "Θέλω να μάθω γιατί…",
        "tr": "Öğrenmek istiyorum çünkü…"
      },
      {
        "el": "Όταν έχω χρόνο, διαβάζω.",
        "tr": "Zamanım olunca okurum."
      },
      {
        "el": "Αν βρέχει, μένω σπίτι.",
        "tr": "Yağmur yağarsa evde kalırım."
      }
    ],
    "steps": [
      "15 bağlaç + örnek listesi.",
      "Bağlaç antrenmanı."
    ],
    "practice": [
      "5 uzun cümle kur."
    ],
    "check": [
      "Aynı bağlacı tekrar tekrar kullanmıyor musun?"
    ],
    "train": "connector"
  },
  "a2-u4-t2": {
    "goal": "A2 okuma: uygulama içi metin + 5 soru.",
    "theory": [
      "YDS → Okuma seti. Dış site yok.",
      "Bilinmeyen kelimeyi bağlamdan tahmin et, sonra karta ekle."
    ],
    "examples": [
      {
        "el": "Ποιο είναι το θέμα;",
        "tr": "Konu nedir?"
      }
    ],
    "steps": [
      "Okuma setinden 2 metin çöz.",
      "Her metin için 3 yeni kelime yaz."
    ],
    "practice": [
      "5 sorunun cevaplarını kontrol et."
    ],
    "check": [
      "Ana fikri doğru işaretledin mi?"
    ]
  },
  "a2-u4-t3": {
    "goal": "Arkadaşa 120 kelimelik e-posta (geçmiş + gelecek).",
    "theory": [
      "Selam + haber (aorist) + plan (θα) + soru + kapanış."
    ],
    "examples": [
      {
        "el": "Γεια σου…",
        "tr": "Merhaba…"
      },
      {
        "el": "Χθες πήγα…",
        "tr": "Dün gittim…"
      },
      {
        "el": "Το Σαββατοκύριακο θα…",
        "tr": "Hafta sonu …acağım."
      },
      {
        "el": "Γράψε μου!",
        "tr": "Yaz bana!"
      }
    ],
    "steps": [
      "120 kelime yaz.",
      "Geçmiş/gelecek fiilleri renklendir.",
      "Sesli oku."
    ],
    "practice": [
      "Zaman kayması var mı kontrol et."
    ],
    "check": [
      "120+ kelime ve iki zaman dilimi var mı?"
    ]
  },
  "a2-u4-t4": {
    "goal": "A2 kapı: geçmiş/gelecek + 200 kelimelik metin öz değerlendirme.",
    "theory": [
      "Mini sınav + yazma + yanlış tekrarı.",
      "Eksik konuları Yol haritasında işaretle."
    ],
    "examples": [],
    "steps": [
      "Mini sınav.",
      "200 kelimelik serbest metin (dün+yarın).",
      "Zayıf liste çıkar."
    ],
    "practice": [
      "%70+ ve metin tamam mı?"
    ],
    "check": [
      "Bir sonraki seviyeye geçmeye hazır mısın?"
    ],
    "train": "exam"
  },
  "a2-u5-t1": {
    "goal": "Doğrudan nesne zamirleri: με σε τον την το…",
    "theory": [
      "Τον βλέπω. Την ξέρω. Το θέλω. Με καταλαβαίνει;",
      "Cinsiyet/sayı uyumu."
    ],
    "examples": [
      {
        "el": "Τον βλέπω.",
        "tr": "Onu (eril) görüyorum."
      },
      {
        "el": "Την καλω.",
        "tr": "Onu (dişil) arıyorum."
      },
      {
        "el": "Το θέλω.",
        "tr": "Onu (nötr) istiyorum."
      },
      {
        "el": "Με βοηθάς;",
        "tr": "Bana yardım ediyor musun?"
      }
    ],
    "steps": [
      "Tablo + 20 cümle.",
      "Zamir antrenmanı.",
      "İsimli cümleyi zamirliye çevir."
    ],
    "practice": [
      "10 dönüşüm yap."
    ],
    "check": [
      "τον/την/το karışıyor mu?"
    ],
    "train": "pronoun"
  },
  "a2-u5-t2": {
    "goal": "Çift zamir giriş: Μου το δίνει.",
    "theory": [
      "Sıra: dolaylı + doğrudan (Μου το…). Emirde sonda: Δώσ' το μου."
    ],
    "examples": [
      {
        "el": "Μου το δίνει.",
        "tr": "Bana onu veriyor."
      },
      {
        "el": "Σου το λέω.",
        "tr": "Sana onu söylüyorum."
      },
      {
        "el": "Δώσ' το μου.",
        "tr": "Ver onu bana."
      }
    ],
    "steps": [
      "Çift zamir antrenmanı.",
      "8 cümle ezber."
    ],
    "practice": [
      "Σου το λέω tipini 5 varyasyon."
    ],
    "check": [
      "Sırayı ters çevirmiyor musun?"
    ],
    "train": "dblpron"
  },
  "a2-u5-t3": {
    "goal": "Garson diyaloğunda zamir kullanmak.",
    "theory": [
      "Sipariş + «Σας το φέρνω αμέσως» tipinde kalıplar."
    ],
    "examples": [
      {
        "el": "Σας το φέρνω.",
        "tr": "Size onu getiriyorum."
      },
      {
        "el": "Μου φέρνετε τον λογαριασμό;",
        "tr": "Hesabı getirir misiniz?"
      }
    ],
    "steps": [
      "Restoran + çift zamir.",
      "1 dk rol kaydı."
    ],
    "practice": [
      "Diyalogda en az 3 zamir."
    ],
    "check": [
      "Doğal duruyor mu?"
    ],
    "train": "restaurant"
  },
  "b1-u1-t1": {
    "goal": "να yapısı: istek, amaç, zorunluluk.",
    "theory": [
      "Θέλω να μάθω. Πρέπει να διαβάσω. Για να καταλάβω…",
      "να’dan sonra kişi çekimli fiil (subjunctive gövdesi)."
    ],
    "examples": [
      {
        "el": "Θέλω να μάθω ελληνικά.",
        "tr": "Yunanca öğrenmek istiyorum."
      },
      {
        "el": "Πρέπει να φύγω.",
        "tr": "Gitmeliyim."
      },
      {
        "el": "Για να καταλάβω, διαβάζω αργά.",
        "tr": "Anlamak için yavaş okuyorum."
      }
    ],
    "steps": [
      "25 cümle (θέλω/πρέπει/για να).",
      "να aspect antrenmanı.",
      "Particle θα/να."
    ],
    "practice": [
      "10 cümleyi sesli oku."
    ],
    "check": [
      "να’dan sonra fiili doğru seçiyor musun?"
    ],
    "train": "subjunctive"
  },
  "b1-u1-t2": {
    "goal": "να γράψω vs να γράφω: aspect bilinci.",
    "theory": [
      "να + aorist gövde ≈ bir kez/bitmiş niyet. να + present ≈ süre/alışkanlık.",
      "Θέλω να σου γράψω (bir mesaj). Θέλω να γράφω καλύτερα (sürekli gelişim)."
    ],
    "examples": [
      {
        "el": "Θέλω να πάω.",
        "tr": "Gitmek istiyorum (bir kez)."
      },
      {
        "el": "Θέλω να πηγαίνω κάθε μέρα.",
        "tr": "Her gün gitmek istiyorum."
      }
    ],
    "steps": [
      "να aspect antrenmanı 2 tur.",
      "10 çift cümle yaz."
    ],
    "practice": [
      "Farkı Türkçe + örnek açıkla."
    ],
    "check": [
      "Aspect’i rastgele sorularda doğru seçiyor musun?"
    ],
    "train": "subjunctive"
  },
  "b1-u1-t3": {
    "goal": "Arkadaşa 5 tavsiye (πρέπει να / καλό είναι να…).",
    "theory": [
      "Tavsiye dili: Πρέπει να… Καλό είναι να… Μη…"
    ],
    "examples": [
      {
        "el": "Πρέπει να κοιμάσαι περισσότερο.",
        "tr": "Daha çok uyumalısın."
      },
      {
        "el": "Καλό είναι να διαβάζεις κάθε μέρα.",
        "tr": "Her gün okuman iyi olur."
      },
      {
        "el": "Μην αργείς.",
        "tr": "Geç kalma."
      }
    ],
    "steps": [
      "5 tavsiye yaz + söyle.",
      "Olumsuz emir antrenmanı.",
      "Kaydet."
    ],
    "practice": [
      "Tavsiyeler çeşitli konularda mı?"
    ],
    "check": [
      "Nazik üslubu koruyor musun?"
    ],
    "train": "negimp"
  },
  "b1-u2-t1": {
    "goal": "Pasif şimdiki: γράφεται, λέγεται, γίνεται.",
    "theory": [
      "Haber/akademik dilde sık. Το βιβλίο γράφεται στα ελληνικά."
    ],
    "examples": [
      {
        "el": "Λέγεται ότι…",
        "tr": "Deniliyor ki…"
      },
      {
        "el": "Γίνεται κάθε χρόνο.",
        "tr": "Her yıl yapılır."
      },
      {
        "el": "Το πρόβλημα λύεται.",
        "tr": "Sorun çözülür."
      }
    ],
    "steps": [
      "Pasif antrenmanı.",
      "8 haber cümlesi yaz."
    ],
    "practice": [
      "Aktifi pasife çevir (5)."
    ],
    "check": [
      "-μαι ekini tanıyor musun?"
    ],
    "train": "passive"
  },
  "b1-u2-t2": {
    "goal": "Orta çatı / dönüşlü: σκέφτομαι, θυμάμαι, φοβάμαι…",
    "theory": [
      "Anlam çoğu zaman ‘kendi…’ veya özel sözlük anlamı. Çekimi pasife benzer."
    ],
    "examples": [
      {
        "el": "Σκέφτομαι να φύγω.",
        "tr": "Gitmeyi düşünüyorum."
      },
      {
        "el": "Θυμάμαι το όνομα.",
        "tr": "İsmi hatırlıyorum."
      },
      {
        "el": "Φοβάμαι τα σκυλιά.",
        "tr": "Köpeklerden korkuyorum."
      },
      {
        "el": "Ντρέπομαι λίγο.",
        "tr": "Biraz utanıyorum."
      }
    ],
    "steps": [
      "Dönüşlü antrenmanı.",
      "15 fiil + cümle listesi."
    ],
    "practice": [
      "10 fiili ezbere cümlede kullan."
    ],
    "check": [
      "Aktif ile karıştırmıyor musun?"
    ],
    "train": "reflexive"
  },
  "b1-u2-t3": {
    "goal": "Kısa haber/metin oku → 80 kelimelik Yunanca özet.",
    "theory": [
      "Kaynak: uygulama Okuma seti / YDS cloze metinleri.",
      "Özet: kim, ne, nerede, sonuç."
    ],
    "examples": [
      {
        "el": "Σύμφωνα με το κείμενο…",
        "tr": "Metne göre…"
      }
    ],
    "steps": [
      "1 okuma metni bitir.",
      "80 kelime özet yaz.",
      "Yeni 5 kelimeyi karta ekle."
    ],
    "practice": [
      "Özet ana fikri kapsıyor mu?"
    ],
    "check": [
      "Kopyala-yapıştır olmadan kendi cümlelerin mi?"
    ]
  },
  "b1-u3-t1": {
    "goal": "Tip 1 koşul: Αν έχει χρόνο, θα έρθει.",
    "theory": [
      "Gerçek/mümkün durum. Αν + şimdiki / θα + gelecek sık."
    ],
    "examples": [
      {
        "el": "Αν βρέχει, θα μείνω σπίτι.",
        "tr": "Yağmur yağarsa evde kalacağım."
      },
      {
        "el": "Αν έχεις χρόνο, έλα.",
        "tr": "Zamanın varsa gel."
      }
    ],
    "steps": [
      "Koşul antrenmanı.",
      "15 Tip 1 cümle."
    ],
    "practice": [
      "5 senaryo için koşul kur."
    ],
    "check": [
      "Αν… θα… kalıbı oturdu mu?"
    ],
    "train": "conditional"
  },
  "b1-u3-t2": {
    "goal": "Tip 2 hayali: Αν είχα…, θα ταξίδευα.",
    "theory": [
      "Karşıolgusal: imperfect + θα + imperfect."
    ],
    "examples": [
      {
        "el": "Αν είχα χρήματα, θα ταξίδευα.",
        "tr": "Param olsaydı seyahat ederdim."
      },
      {
        "el": "Αν ήξερα, θα το έλεγα.",
        "tr": "Bilsem söylerdim."
      }
    ],
    "steps": [
      "15 Tip 2 cümle.",
      "Koşul antrenmanı.",
      "Yanlış düzelt antrenmanı."
    ],
    "practice": [
      "Tip 1 ile Tip 2’yi ayırt et (5 çift)."
    ],
    "check": [
      "Çekimlerde παρατατικός doğru mu?"
    ],
    "train": "conditional"
  },
  "b1-u3-t3": {
    "goal": "3 konuda 1’er dk «Αν…» konuşması.",
    "theory": [
      "Konular: para, zaman, dil öğrenme. Kaydet."
    ],
    "examples": [
      {
        "el": "Αν μπορούσα…",
        "tr": "Yapabilseydim…"
      }
    ],
    "steps": [
      "3 monolog kaydı.",
      "Her birinde en az 4 koşul cümlesi."
    ],
    "practice": [
      "Kayıtlarda dolgu (εεε) sayısını not et."
    ],
    "check": [
      "3 dk toplam akıcı mı?"
    ]
  },
  "b1-u4-t1": {
    "goal": "Tematik kelime: iş, sağlık, eğitim, çevre, teknoloji.",
    "theory": [
      "Her temadan uygulama desteleri + yeni liste. Hedef tema başı ~40."
    ],
    "examples": [
      {
        "el": "προθεσμία",
        "tr": "son tarih"
      },
      {
        "el": "ραντεβού",
        "tr": "randevu"
      },
      {
        "el": "περιβάλλον",
        "tr": "çevre"
      },
      {
        "el": "έρευνα",
        "tr": "araştırma"
      }
    ],
    "steps": [
      "Kartlar: İş, Sağlık, Okul, Teknoloji, Doğa.",
      "Her desteden tur at.",
      "40×5 hedefe doğru ilerle."
    ],
    "practice": [
      "Her temadan 10 kelime TR→EL."
    ],
    "check": [
      "Zayıf temayı işaretledin mi?"
    ]
  },
  "b1-u4-t2": {
    "goal": "30 eş/zıt anlamlı çift.",
    "theory": [
      "Zıt + eşanlam antrenmanları. YDS tuzakları için kritik."
    ],
    "examples": [
      {
        "el": "μεγάλος–μικρός",
        "tr": "büyük–küçük"
      },
      {
        "el": "αρχίζω–τελειώνω",
        "tr": "başla–bitir"
      },
      {
        "el": "αλλά ≈ όμως",
        "tr": "ama"
      }
    ],
    "steps": [
      "Zıt + Eşanlam antrenmanları.",
      "30 çift tablo."
    ],
    "practice": [
      "15’ini ezbere sor."
    ],
    "check": [
      "False friend ile karıştırmıyor musun?"
    ],
    "train": "opposite"
  },
  "b1-u4-t3": {
    "goal": "15 dk dinleme notu (uygulama TTS + dinle-anla).",
    "theory": [
      "Dış podcast zorunlu değil. Dinle-anla + dikte + günün kalıbı zinciri."
    ],
    "examples": [
      {
        "el": "Η κεντρική ιδέα είναι…",
        "tr": "Ana fikir…"
      }
    ],
    "steps": [
      "Dinle-anla 3 tur.",
      "8 anahtar kelime + 3 cümle özet."
    ],
    "practice": [
      "Özeti sesli söyle."
    ],
    "check": [
      "Ana fikri doğru yakaladın mı?"
    ],
    "train": "listen"
  },
  "b1-u4-t4": {
    "goal": "B1 kapı: okuma + dilbilgisi + 200 kelimelik görüş.",
    "theory": [
      "Mini sınav + okuma + yazma. Zayıf alanı Yol’da aç."
    ],
    "examples": [],
    "steps": [
      "Mini sınav.",
      "Okuma 2 metin.",
      "200 kelime görüş (Αν… / πρέπει να… kullan)."
    ],
    "practice": [
      "Skor ve eksik listesi."
    ],
    "check": [
      "B1 hedeflerinin çoğunu karşılıyor musun?"
    ],
    "train": "exam"
  },
  "b1-u5-t1": {
    "goal": "που göreli: Ο άνθρωπος που…",
    "theory": [
      "που ≈ ki / -en/-an. Tanımlayıcı bilgi."
    ],
    "examples": [
      {
        "el": "Ο άνθρωπος που μιλάει είναι γιατρός.",
        "tr": "Konuşan adam doktor."
      },
      {
        "el": "Το βιβλίο που διάβασα ήταν καλό.",
        "tr": "Okuduğum kitap iyiydi."
      }
    ],
    "steps": [
      "που antrenmanı.",
      "15 cümle yaz."
    ],
    "practice": [
      "5 kişiyi που ile tanıt."
    ],
    "check": [
      "που’yu και ile değiştirmiyor musun?"
    ],
    "train": "relative"
  },
  "b1-u5-t2": {
    "goal": "Tanımlayıcı vs ek bilgi (virgül / ο οποίος farkına giriş).",
    "theory": [
      "Konuşmada που çok yaygındır. Yazıda ο οποίος daha resmi olabilir.",
      "Virgülden sonraki bilgi çoğu zaman ek bilgidir."
    ],
    "examples": [
      {
        "el": "Ο φίλος μου που μένει στην Αθήνα…",
        "tr": "Atina’da yaşayan arkadaşım (tanımlayıcı)"
      },
      {
        "el": "Ο Νίκος, που είναι γιατρός, …",
        "tr": "Nikos, ki doktordur, … (ek bilgi)"
      }
    ],
    "steps": [
      "6 çift cümle yaz (tanımlayıcı/ek).",
      "που antrenmanı."
    ],
    "practice": [
      "Farkı örnekle açıkla."
    ],
    "check": [
      "Bağlamda hangisi olduğunu söyleyebiliyor musun?"
    ]
  },
  "b1-u5-t3": {
    "goal": "3 kişiyi που ile uzun cümlede anlatmak.",
    "theory": [
      "Ad + meslek + şehir + bir özellik, hepsi που ile bağlanabilir."
    ],
    "examples": [
      {
        "el": "Η Μαρία που δουλεύει στην Αθήνα και που αγαπάει τον καφέ…",
        "tr": "Atina’da çalışan ve kahveyi seven Maria…"
      }
    ],
    "steps": [
      "3 paragraf konuş/yaz.",
      "Kaydet."
    ],
    "practice": [
      "Her kişide en az 2 που."
    ],
    "check": [
      "Akıcılık kabul edilebilir mi?"
    ]
  },
  "b2-u1-t1": {
    "goal": "έχω γράψει (παρακείμενος): geçmişin şimdiki sonucu.",
    "theory": [
      "Perfect: έχω + απαρέμφατο. Έχω τελειώσει = bitirmişim (sonuç duruyor)."
    ],
    "examples": [
      {
        "el": "Έχω γράψει το μήνυμα.",
        "tr": "Mesajı yazmış bulunuyorum."
      },
      {
        "el": "Έχεις πάει στην Ελλάδα;",
        "tr": "Yunanistan’a gittin mi (hiç)?"
      }
    ],
    "steps": [
      "Perfect antrenmanı.",
      "20 cümle.",
      "Aorist ile karşılaştır 5 çift."
    ],
    "practice": [
      "10 perfect cümle."
    ],
    "check": [
      "Ne zaman perfect seçeceğini açıklayabiliyor musun?"
    ],
    "train": "perfect"
  },
  "b2-u1-t2": {
    "goal": "Dolaylı anlatım: Είπε ότι… Ρώτησε αν… Μου είπε να…",
    "theory": [
      "Aktarımda zaman/kişi kayması olabilir; B2’de kalıpları ezberle."
    ],
    "examples": [
      {
        "el": "Είπε ότι θα έρθει.",
        "tr": "Geleceğini söyledi."
      },
      {
        "el": "Ρώτησε αν είμαι καλά.",
        "tr": "İyi olup olmadığımı sordu."
      },
      {
        "el": "Μου είπε να περιμένω.",
        "tr": "Beklememi söyledi."
      }
    ],
    "steps": [
      "12 dönüşüm: düz → dolaylı.",
      "να + emir aktarımı."
    ],
    "practice": [
      "Mini diyalog aktar."
    ],
    "check": [
      "ότι / αν / να ayrımını biliyor musun?"
    ]
  },
  "b2-u1-t3": {
    "goal": "İleri bağlaçlar: παρόλο που, ενώ, ώστε, εφόσον, ωστόσο…",
    "theory": [
      "Akademik/YDS bağları. Anlam ilişkisi: karşıt, amaç, koşul."
    ],
    "examples": [
      {
        "el": "Παρόλο που βρέχει, θα βγω.",
        "tr": "Yağmur yağmasına rağmen çıkacağım."
      },
      {
        "el": "Διαβάζω ώστε να καταλάβω.",
        "tr": "Anlamak için okuyorum."
      },
      {
        "el": "Ωστόσο, δεν συμφωνώ.",
        "tr": "Yine de katılmıyorum."
      }
    ],
    "steps": [
      "Bağlaç antrenmanı.",
      "40 bağlayıcı kartı (cümleyle).",
      "Cloze setleri."
    ],
    "practice": [
      "10 cümle farklı bağlaç."
    ],
    "check": [
      "YDS’de ilişki türünü önce mi bakıyorsun?"
    ],
    "train": "connector"
  },
  "b2-u2-t1": {
    "goal": "Haftalık haber rutini — uygulama metinleriyle.",
    "theory": [
      "Okuma seti + cloze metinleri «haber» yerine geçer. Her biri: özet + 5 kelime."
    ],
    "examples": [
      {
        "el": "Η είδηση λέει ότι…",
        "tr": "Haber diyor ki…"
      }
    ],
    "steps": [
      "3 okuma metni.",
      "Her biri 40–60 kelime özet + 5 kelime."
    ],
    "practice": [
      "Kelimeleri desteye ekle."
    ],
    "check": [
      "3 özet tamam mı?"
    ]
  },
  "b2-u2-t2": {
    "goal": "Normal hız dinleme pratiği (uygulama içi).",
    "theory": [
      "Dinle-anla + dikte zinciri 8–12 dk. Altyazı yok: önce genel, sonra detay."
    ],
    "examples": [],
    "steps": [
      "Dinle-anla 4 tur.",
      "Dikte 5 cümle.",
      "Not: 8 anahtar ifade."
    ],
    "practice": [
      "İkinci dinlemede detay arttı mı?"
    ],
    "check": [
      "Ana fikir doğru mu?"
    ],
    "train": "listen"
  },
  "b2-u2-t3": {
    "goal": "250–300 kelimelik görüş yazısı (giriş–gelişme–sonuç).",
    "theory": [
      "Tez cümlesi, 2 gerekçe, örnek, sonuç. Bağlaçları bilerek kullan."
    ],
    "examples": [
      {
        "el": "Κατά τη γνώμη μου…",
        "tr": "Bana göre…"
      },
      {
        "el": "Για παράδειγμα…",
        "tr": "Örneğin…"
      },
      {
        "el": "Συμπερασματικά…",
        "tr": "Sonuç olarak…"
      }
    ],
    "steps": [
      "Konu seç (teknoloji/eğitim).",
      "300 kelimeye yaklaş.",
      "Bağlaçları işaretle."
    ],
    "practice": [
      "Yapı net mi?"
    ],
    "check": [
      "Kelime sayısı ve üslup B2’ye yaklaşıyor mu?"
    ]
  },
  "b2-u3-t1": {
    "goal": "Paragraf anatomisi: konu cümlesi, destek, sonuç.",
    "theory": [
      "YDS okuma: önce yapı, sonra şıklar.",
      "Uygulama okuma metinlerinde işaretle."
    ],
    "examples": [
      {
        "el": "Η κεντρική ιδέα βρίσκεται…",
        "tr": "Ana fikir …da"
      }
    ],
    "steps": [
      "5 paragraf/metinde konu cümlesini bul.",
      "Okuma seti."
    ],
    "practice": [
      "Şıkları okumadan önce kendi özetini yaz."
    ],
    "check": [
      "Tuzak şıklara düştün mü? Analiz et."
    ]
  },
  "b2-u3-t2": {
    "goal": "Bağlamdan kelime tahmini.",
    "theory": [
      "Sözlükten önce: tür (fiil/isim), olumlu/olumsuz, yakın anlam.",
      "Sonra kart/deck ile doğrula."
    ],
    "examples": [],
    "steps": [
      "Bir okuma metninde 10 bilinmeyeni tahmin et.",
      "Doğrula, 10 kart yaz."
    ],
    "practice": [
      "Tahmin doğruluk oranını not et."
    ],
    "check": [
      "%50+ mantıklı tahmin?"
    ]
  },
  "b2-u3-t3": {
    "goal": "YDS tarzı 10 soru — süre tut.",
    "theory": [
      "YDS sekmesi: cloze + okuma. Kronometre 12 dk."
    ],
    "examples": [],
    "steps": [
      "Cloze 1 set + okuma soruları.",
      "Süre bitince dur.",
      "Yanlış analizi."
    ],
    "practice": [
      "Soru tipi dağılımını yaz."
    ],
    "check": [
      "Süreye yetişiyor musun?"
    ]
  },
  "b2-u3-t4": {
    "goal": "Hata günlüğü: kelime / yapı / çıkarım / dikkat.",
    "theory": [
      "İlerleme → Hata günlüğü. Her yanlış bir etikete."
    ],
    "examples": [],
    "steps": [
      "Son 10 yanlışı sınıflandır.",
      "Her sınıfa 1 mini alıştırma seç (antrenman)."
    ],
    "practice": [
      "Aynı hata tekrar ediyor mu?"
    ],
    "check": [
      "Günlük güncel mi?"
    ]
  },
  "b2-u4-t1": {
    "goal": "10 konuda 2’şer dk hazırlıksız konuşma.",
    "theory": [
      "Konu örnekleri: iş, tatil, teknoloji, sağlık, dil, şehir, yemek, spor, aile, gelecek."
    ],
    "examples": [],
    "steps": [
      "10 kayıt.",
      "Her birinde giriş+2 nokta+kapanış.",
      "En kötü 3’ü yeniden çek."
    ],
    "practice": [
      "Dolgu kelimelerini say."
    ],
    "check": [
      "2 dk’yı doldurabiliyor musun?"
    ]
  },
  "b2-u4-t2": {
    "goal": "Tezi savunan ve karşı argümanı anlatan konuşma.",
    "theory": [
      "Kalıp: Κατά τη γνώμη μου… Από την άλλη…"
    ],
    "examples": [
      {
        "el": "Από την άλλη πλευρά…",
        "tr": "Öte yandan…"
      }
    ],
    "steps": [
      "Bir tez seç.",
      "2 dk lehte, 2 dk aleyhte kaydet."
    ],
    "practice": [
      "Her iki taraf da mantıklı mı?"
    ],
    "check": [
      "Bağlaçlar yeterli mi?"
    ]
  },
  "b2-u4-t3": {
    "goal": "B2 kapı sınavı: okuma + yazma + 4 dk konuşma.",
    "theory": [
      "Mini sınav + 250 kelime + monolog. Checklist: bağlaç, aspect, kelime."
    ],
    "examples": [],
    "steps": [
      "Sınav + yazı + konuşma.",
      "Eksikleri listele."
    ],
    "practice": [
      "%70+ ve üretim tamam mı?"
    ],
    "check": [
      "C1’e geçiş için zayıf nokta net mi?"
    ],
    "train": "exam"
  },
  "b2-u5-t1": {
    "goal": "Argüman kalıp bankası.",
    "theory": [
      "Κατά τη γνώμη μου, Για παράδειγμα, Επιπλέον, Ωστόσο, Συμπερασματικά…"
    ],
    "examples": [
      {
        "el": "Κατά τη γνώμη μου…",
        "tr": "Bana göre…"
      },
      {
        "el": "Για παράδειγμα…",
        "tr": "Örneğin…"
      },
      {
        "el": "Συμπερασματικά…",
        "tr": "Sonuç olarak…"
      }
    ],
    "steps": [
      "15 kalıp ezber + cümle.",
      "Bağlaç/kolokasyon antrenmanı."
    ],
    "practice": [
      "1 dakikada 5 kalıp kullan."
    ],
    "check": [
      "Kalıplar ezbere geliyor mu?"
    ],
    "train": "collocation"
  },
  "b2-u5-t2": {
    "goal": "300 kelimelik yapılandırılmış görüş yazısı.",
    "theory": [
      "Tez–gerekçe–örnek–sonuç. Önceki kalıp bankasını kullan."
    ],
    "examples": [],
    "steps": [
      "300 kelime yaz.",
      "Her paragrafa işlev etiketi koy."
    ],
    "practice": [
      "Üslup tutarlı mı?"
    ],
    "check": [
      "Kelime sayısı ve yapı tamam mı?"
    ]
  },
  "b2-u5-t3": {
    "goal": "Aynı tezi 3 dk sözlü savun.",
    "theory": [
      "Yazıdan nota geç, ezberleme — konuş."
    ],
    "examples": [],
    "steps": [
      "3 dk kaydet.",
      "Dinle, 3 iyileştirme yap, yeniden kaydet."
    ],
    "practice": [
      "Süre doldu mu?"
    ],
    "check": [
      "Mesaj net mi?"
    ]
  },
  "c1-u1-t1": {
    "goal": "Aynı mesajı samimi / nötr / resmi yazmak.",
    "theory": [
      "Register: οικείο ↔ επίσημο. Fiil seçimi, hitap, bağlaç değişir."
    ],
    "examples": [
      {
        "el": "Γεια! Θα περάσω αργότερα.",
        "tr": "Samimi"
      },
      {
        "el": "Θα ήθελα να σας ενημερώσω ότι…",
        "tr": "Resmi"
      }
    ],
    "steps": [
      "5 mesaj × 3 üslup = 15 versiyon.",
      "Nazik/resmi kalıpları kullan."
    ],
    "practice": [
      "Resmi olanı sesli oku."
    ],
    "check": [
      "Üç üslup gerçekten farklı mı?"
    ],
    "train": "polite"
  },
  "c1-u1-t2": {
    "goal": "Akademik bağlayıcı kartı (≈40).",
    "theory": [
      "εντούτοις, συνεπώς, ιδιαιτέρως, αναμφίβολα, ως εκ τούτου…"
    ],
    "examples": [
      {
        "el": "Εντούτοις…",
        "tr": "Bununla birlikte…"
      },
      {
        "el": "Συνεπώς…",
        "tr": "Dolayısıyla…"
      },
      {
        "el": "Αναμφίβολα…",
        "tr": "Şüphesiz…"
      }
    ],
    "steps": [
      "40 ifade + örnek.",
      "Bağlaç antrenmanı + cloze.",
      "YDS kelime destesi."
    ],
    "practice": [
      "20’sini TR→EL."
    ],
    "check": [
      "Yazıda en az 8’ini kullanabiliyor musun?"
    ],
    "train": "connector"
  },
  "c1-u1-t3": {
    "goal": "Uzun metin özeti (200 kelime) — uygulama okumaları zinciri.",
    "theory": [
      "2–3 okuma metnini birleştirip tek akademik özete dönüştür."
    ],
    "examples": [
      {
        "el": "Το κείμενο υποστηρίζει ότι…",
        "tr": "Metin şunu savunuyor…"
      }
    ],
    "steps": [
      "Okuma seti yoğun.",
      "200 kelime özet, bağlayıcılı."
    ],
    "practice": [
      "Özet tarafsız mı?"
    ],
    "check": [
      "Kişisel yorum ile özeti ayırdın mı?"
    ]
  },
  "c1-u2-t1": {
    "goal": "50 deyim: anlam + örnek + Türkçe.",
    "theory": [
      "Örnek set (hepsini cümleyle genişlet): τα βρήκαμε (anlaştık), μου ήρθε (aklıma geldi), κάνω κουράγιο (cesaret bul), δεν βαριέσαι (boş ver), όλα καλά, άστο, ρίχνω μια ματιά, παίρνω θάρρος, χάνω το δίκιο μου, είμαι στα κέφια μου…"
    ],
    "examples": [
      {
        "el": "Τα βρήκαμε.",
        "tr": "Anlaştık."
      },
      {
        "el": "Ρίξε μια ματιά.",
        "tr": "Bir göz at."
      },
      {
        "el": "Δεν βαριέσαι.",
        "tr": "Boş ver / ne yapalım."
      }
    ],
    "steps": [
      "50 satırlık tablo doldur.",
      "Günün kalıplarını ekle.",
      "10’unu konuşmada kullan."
    ],
    "practice": [
      "20 rastgele soru."
    ],
    "check": [
      "Deyimi kelimesi kelimesine çevirmiyor musun?"
    ]
  },
  "c1-u2-t2": {
    "goal": "10 düz cümleyi doğal/idiomatik hale getirmek.",
    "theory": [
      "Literal Türkçe düşünceyi Yunanca kalıba çevir."
    ],
    "examples": [
      {
        "el": "Είμαι πολύ κουρασμένος.",
        "tr": "→ Πεθαίνω από την κούραση (bağlama göre)"
      }
    ],
    "steps": [
      "10 dönüşüm yaz.",
      "Native gibi mi diye sesli oku."
    ],
    "practice": [
      "3 versiyonu kaydet."
    ],
    "check": [
      "Abartılı/yanlış deyim kullanmadın mı?"
    ]
  },
  "c1-u2-t3": {
    "goal": "Native içerik yerine yoğun dinleme notu (uygulama).",
    "theory": [
      "20 dk: dinle-anla + dikte + kalıp tekrarı. Yeni ifadeleri listele."
    ],
    "examples": [],
    "steps": [
      "20 dk kronometre.",
      "12 ifade listesi.",
      "3’ünü cümlede kullan."
    ],
    "practice": [
      "Liste aktif mi?"
    ],
    "check": [
      "Pasif dinleme olmadı mı?"
    ],
    "train": "dictation"
  },
  "c1-u3-t1": {
    "goal": "Cloze stratejisi: dilbilgisi ipucu + kolokasyon.",
    "theory": [
      "Önce boşluğun türü (edat/fiil/bağlaç). Sonra anlam.",
      "YDS → Cloze setleri."
    ],
    "examples": [],
    "steps": [
      "3 cloze seti.",
      "Her yanlışta «neden» yaz."
    ],
    "practice": [
      "Strateji notunu 5 madde yap."
    ],
    "check": [
      "İlk şık tuzağına düşmeyi azalttın mı?"
    ]
  },
  "c1-u3-t2": {
    "goal": "YDS akademik kelime bankası (hedef 200, uygulama destesiyle).",
    "theory": [
      "YDS destesi + extras kelimeler. Her kelimeye 1 üretim cümlesi."
    ],
    "examples": [
      {
        "el": "υπόθεση",
        "tr": "varsayım"
      },
      {
        "el": "συμπέρασμα",
        "tr": "sonuç"
      },
      {
        "el": "επίδραση",
        "tr": "etki"
      },
      {
        "el": "αξιολόγηση",
        "tr": "değerlendirme"
      }
    ],
    "steps": [
      "YDS kart turları.",
      "Günde 20 yeni + 20 tekrar.",
      "Cümle üret."
    ],
    "practice": [
      "50 kelimeyi aktif kullanabiliyor musun?"
    ],
    "check": [
      "Sadece tanıma mı kaldı?"
    ]
  },
  "c1-u3-t3": {
    "goal": "Zamanlı deneme parçası: 20 soru.",
    "theory": [
      "Mini sınav + cloze + okuma. Analiz zorunlu."
    ],
    "examples": [],
    "steps": [
      "20 soru süreyle.",
      "Otopsi.",
      "Zayıf tip kampı planla."
    ],
    "practice": [
      "Skor kaydı."
    ],
    "check": [
      "Aynı hatalar tekrar ediyor mu?"
    ],
    "train": "exam"
  },
  "c1-u4-t1": {
    "goal": "400 kelimelik toplumsal deneme.",
    "theory": [
      "Giriş–tez–2 gövde–karşı görüş–sonuç. Akademik bağlayıcı zorunlu."
    ],
    "examples": [],
    "steps": [
      "400 kelime.",
      "Bağlayıcıları say (≥10).",
      "Bir gün sonra düzenle."
    ],
    "practice": [
      "Yapı C1 mi?"
    ],
    "check": [
      "Tekrarlayan kelimeyi azalttın mı?"
    ]
  },
  "c1-u4-t2": {
    "goal": "5 dk slaytsız sunum kaydı.",
    "theory": [
      "Giriş, 3 nokta, sonuç. Dolgu azalt."
    ],
    "examples": [],
    "steps": [
      "Taslak 8 satır.",
      "5 dk kaydet.",
      "Dinle, dolguları işaretle, yeniden."
    ],
    "practice": [
      "İkinci kayıt daha temiz mi?"
    ],
    "check": [
      "Süre ve netlik tamam mı?"
    ]
  },
  "c1-u4-t3": {
    "goal": "C1 kapı: zor metin + deneme + dinleme checklist.",
    "theory": [
      "Okuma zor set + 300 kelime + dinleme turu. Can-do listesi işaretle."
    ],
    "examples": [],
    "steps": [
      "Üç parçayı bitir.",
      "Checklist yaz."
    ],
    "practice": [
      "Zayıf kutu net mi?"
    ],
    "check": [
      "C2’ye geçiş için ne eksik?"
    ]
  },
  "c1-u5-t1": {
    "goal": "40 söylem bağlayıcısı listesi (karşıt/neden/ekleme/örnek).",
    "theory": [
      "Metin tutarlılığı için. Önceki akademik seti genişlet."
    ],
    "examples": [],
    "steps": [
      "4 kategori × 10.",
      "Her birine cümle.",
      "Bağlaç antrenmanı."
    ],
    "practice": [
      "Ezber testi 20 soru."
    ],
    "check": [
      "Yazıda çeşitlilik var mı?"
    ],
    "train": "connector"
  },
  "c1-u5-t2": {
    "goal": "Zayıf paragrafı akademik üsluba çevirmek.",
    "theory": [
      "Kısa cümleleri birleştir; bağlayıcı ekle; tekrarı kır."
    ],
    "examples": [],
    "steps": [
      "Kendi eski yazından 1 paragraf seç.",
      "Yeniden yaz.",
      "Önce/sonra karşılaştır."
    ],
    "practice": [
      "Üslup yükseldi mi?"
    ],
    "check": [
      "Anlam bozulmadı mı?"
    ]
  },
  "c1-u5-t3": {
    "goal": "Eski yazında 5 bağlayıcı hatası bul ve düzelt.",
    "theory": [
      "Yanlış ilişki, gereks fazla ωστόσο, eksik bağ…"
    ],
    "examples": [],
    "steps": [
      "5 hata + düzeltme.",
      "Hata günlüğüne ekle."
    ],
    "practice": [
      "Aynı hatayı bir daha yapmamak için kural yaz."
    ],
    "check": [
      "5/5 düzeltildi mi?"
    ]
  },
  "c2-u1-t1": {
    "goal": "Edebi üslup analizi — uygulama içi edebiyat parçası.",
    "theory": [
      "Metin: «Το πρωί η πόλη μύριζε θάλασσα και φρεσκοψημένο ψωμί. Οι άνθρωποι περπατούσαν αργά, σαν να μην τους βιάζει κανένας χρόνος. Κάπου μακριά, μια καμπάνα θύμιζε ότι η μέρα είχε επίσημα αρχίσει.»",
      "Görev: imgeler, tempo, tekrar eden sesler, anlatıcı tutumu."
    ],
    "examples": [
      {
        "el": "μύριζε",
        "tr": "kokuyordu"
      },
      {
        "el": "σαν να…",
        "tr": "sanki…"
      }
    ],
    "steps": [
      "Metni 2 kez oku.",
      "Türkçe 150 kelime üslup analizi yaz.",
      "5 edebi kelimeyi ezberle."
    ],
    "practice": [
      "Analizde en az 3 üslup özelliği."
    ],
    "check": [
      "Sadece özet değil, üslup konuştun mu?"
    ]
  },
  "c2-u1-t2": {
    "goal": "Kültürel kavram kartları (φιλότιμο vb.).",
    "theory": [
      "φιλότιμο: onur + gönüllü fedakârlık karışımı. κέφι: neşe/keyif hali. καφενείο: sosyal alan. φιλόξενια: misafirperverlik. μεράκι: işe tutkuyla bağlanma. παλικαριά: yiğitlik. μοίρα: kader. χωριό: köy kimliği. θάλασσα: kültürel motif. ιστορία: geçmişle bağ."
    ],
    "examples": [
      {
        "el": "φιλότιμο",
        "tr": "onur / gönüllü sorumluluk duygusu"
      },
      {
        "el": "φιλοξενία",
        "tr": "misafirperverlik"
      },
      {
        "el": "μεράκι",
        "tr": "tutkuyla yapılan iş"
      }
    ],
    "steps": [
      "10 kavram kartı: tanım + örnek cümle + kişisel yorum.",
      "3’ünü konuşmada kullan."
    ],
    "practice": [
      "Kartları sesli anlat."
    ],
    "check": [
      "Türkçe’ye birebir zorlama çeviri yapmadın mı?"
    ]
  },
  "c2-u1-t3": {
    "goal": "Mizah/ironi: neden komik?",
    "theory": [
      "Örnek: «Θα φτάσω σε πέντε λεπτά» — Yunanistan’da bazen esnek zaman; abartı ve ortak bilgi mizah yaratır.",
      "İroni: söylenen ≠ kastedilen. Ton + bağlam."
    ],
    "examples": [],
    "steps": [
      "3 örnek yaz (kendi veya metinden).",
      "Her birinde mekanizma: abartı/ironi/kelime oyunu.",
      "Sesli anlat."
    ],
    "practice": [
      "Açıklama Türkçe net mi?"
    ],
    "check": [
      "Kültürel varsayımı yazdın mı?"
    ]
  },
  "c2-u2-t1": {
    "goal": "Kendi alanından 100 terim (Yunanca tanım).",
    "theory": [
      "Meslek/okul alanın. Her satır: terim — Yunanca tanım — örnek."
    ],
    "examples": [],
    "steps": [
      "100 satır tablo.",
      "Günde 20.",
      "10’unu sunumda kullan."
    ],
    "practice": [
      "Tanımlar Yunanca mı (Türkçe kaçak az)?"
    ],
    "check": [
      "Aktif kullanım var mı?"
    ]
  },
  "c2-u2-t2": {
    "goal": "Alanından konuyu 8–10 dk Yunanca anlatmak.",
    "theory": [
      "Giriş, tanımlar, örnek, sonuç. Terim listeni kullan."
    ],
    "examples": [],
    "steps": [
      "Taslak.",
      "10 dk kaydet.",
      "Anlaşılırlık için sadeleştir, yeniden kaydet."
    ],
    "practice": [
      "Terimler doğru mu?"
    ],
    "check": [
      "Dinleyici varsayımı net mi?"
    ]
  },
  "c2-u2-t3": {
    "goal": "Teknik özet 300 kelime.",
    "theory": [
      "Makale/rapor yerine: kendi alan notların + uygulama akademik kelimeleri."
    ],
    "examples": [],
    "steps": [
      "300 kelime özet.",
      "Jargon + bağlayıcı dengesi."
    ],
    "practice": [
      "Özet tarafsız ve yoğun mu?"
    ],
    "check": [
      "C2 yoğunluğu var mı?"
    ]
  },
  "c2-u3-t1": {
    "goal": "İnce yapı bankası: nadir ama güçlü kalıplar.",
    "theory": [
      "όσο + karşılaştırma, είτε… είτε…, αντι να…, χωρίς να…, με το να…, το να + fiil (isimleştirme), όχι μόνο… αλλά και…"
    ],
    "examples": [
      {
        "el": "Αντί να φύγω, έμεινα.",
        "tr": "Gitmek yerine kaldım."
      },
      {
        "el": "Χωρίς να το καταλάβω…",
        "tr": "Anlamadan…"
      },
      {
        "el": "Το να μαθαίνεις κάθε μέρα βοηθάει.",
        "tr": "Her gün öğrenmek yardım eder."
      }
    ],
    "steps": [
      "12 yapı × 2 cümle.",
      "Eski yazına 5’ini yerleştir."
    ],
    "practice": [
      "Doğallık kontrolü."
    ],
    "check": [
      "Zorlama üslup olmadı mı?"
    ]
  },
  "c2-u3-t2": {
    "goal": "Eski yazını C2 üslubuna yeniden yazmak.",
    "theory": [
      "Daha yoğun bağlaç, daha az tekrar, daha net tez."
    ],
    "examples": [],
    "steps": [
      "Eski B2/C1 yazısını seç.",
      "Yeniden yaz.",
      "Önce/sonra kelime çeşitliliği say."
    ],
    "practice": [
      "İyileşme somut mu?"
    ],
    "check": [
      "Anlam aynı, üslup üstün mü?"
    ]
  },
  "c2-u3-t3": {
    "goal": "CEFR C2 can-do öz değerlendirme.",
    "theory": [
      "Uzun metin zahmetsiz mi? Nüans/ironi? Alan dili? Doğaçlama konuşma?"
    ],
    "examples": [],
    "steps": [
      "10 can-do maddesi yaz, 1–5 puanla.",
      "≤3 olanlara görev bağla."
    ],
    "practice": [
      "Dürüst puanlama."
    ],
    "check": [
      "Gelişim planı çıktı mı?"
    ]
  },
  "c2p-u1-t1": {
    "goal": "Tam deneme #1 — uygulama sınav + cloze + okuma zinciri.",
    "theory": [
      "Gerçek süre: Mini sınav + ek cloze/okuma ile ~uzun oturum. Ham skor kaydet."
    ],
    "examples": [],
    "steps": [
      "Süre tut.",
      "Cevapları işaretle.",
      "Skoru İlerleme/günlüğe yaz."
    ],
    "practice": [
      "Kesinti olmadı mı?"
    ],
    "check": [
      "Ham skor not edildi mi?"
    ],
    "train": "exam"
  },
  "c2p-u1-t2": {
    "goal": "Hata otopsi: neden + kural + benzer 2 soru.",
    "theory": [
      "Her yanlış için: kök neden, kural, 2 benzer soru üret (kendine)."
    ],
    "examples": [],
    "steps": [
      "Tüm yanlışları tablola.",
      "Antrenmana bağla.",
      "Hata günlüğü."
    ],
    "practice": [
      "Her satır dolu mu?"
    ],
    "check": [
      "Aynı tip tekrar etmesin diye plan var mı?"
    ]
  },
  "c2p-u1-t3": {
    "goal": "En zayıf soru tipinde 3 gün yoğun set.",
    "theory": [
      "Cloze mi, okuma çıkarımı mı, bağlaç mı? O antrenmanı günde 2 blok."
    ],
    "examples": [],
    "steps": [
      "Zayıf tipi seç.",
      "3 gün × ilgili antrenman/drill.",
      "Mini ölçüm."
    ],
    "practice": [
      "Skor yükseldi mi?"
    ],
    "check": [
      "Tip hâlâ zayıf mı?"
    ]
  },
  "c2p-u1-t4": {
    "goal": "Tam deneme #2 — iyileşmeyi ölç.",
    "theory": [
      "Aynı koşullar. #1 ile karşılaştır."
    ],
    "examples": [],
    "steps": [
      "Deneme.",
      "Fark tablosu.",
      "Yeni zayıf tip."
    ],
    "practice": [
      "Tutarlı band?"
    ],
    "check": [
      "Bir sonraki döngü planı?"
    ],
    "train": "exam"
  },
  "c2p-u2-t1": {
    "goal": "Haftalık uzun okuma + kelime defteri.",
    "theory": [
      "Okuma setlerini birleştir; 1 uzun oturum. Deftere 15 kelime."
    ],
    "examples": [],
    "steps": [
      "60 dk okuma.",
      "15 kelime + cümle.",
      "1 özet."
    ],
    "practice": [
      "Rutin bu hafta işledi mi?"
    ],
    "check": [
      "Kelimeler tekrar listesine girdi mi?"
    ]
  },
  "c2p-u2-t2": {
    "goal": "Haftalık 45 dk dinleme bakımı.",
    "theory": [
      "Dinle-anla + dikte + kalıp. Not al."
    ],
    "examples": [],
    "steps": [
      "45 dk.",
      "10 ifade.",
      "3 üretim cümlesi."
    ],
    "practice": [
      "Pasif kalmadın mı?"
    ],
    "check": [
      "İfadeler aktif mi?"
    ],
    "train": "listen"
  },
  "c2p-u2-t3": {
    "goal": "Haftalık üretim: deneme veya 10 dk konuşma.",
    "theory": [
      "Birini seç, bitir, kaydet/ arşivle."
    ],
    "examples": [],
    "steps": [
      "Üretim yap.",
      "1 hata listesi çıkar.",
      "Düzeltme sürümü."
    ],
    "practice": [
      "Üretim tamam mı?"
    ],
    "check": [
      "Gerileme sinyali var mı?"
    ]
  },
  "c2p-u2-t4": {
    "goal": "Aylık seviye kontrolü.",
    "theory": [
      "Kısa deneme + konuşma. Gerileme varsa ilgili birime dön (Yol haritası)."
    ],
    "examples": [],
    "steps": [
      "Mini sınav + 3 dk konuşma.",
      "Can-do güncelle.",
      "Geri dönüş görevi seç."
    ],
    "practice": [
      "Karar net mi?"
    ],
    "check": [
      "Takvimde gelecek ay kontrolü var mı?"
    ],
    "train": "exam"
  }
};

const Lessons = {
  get(taskId) {
    return LESSONS[taskId] || null;
  },
  allIds() {
    return Object.keys(LESSONS);
  }
};
